### ISSUE TITLE
Number format in table view

### ISSUE THREAD

**Issue by mousspi** [binjr/binjr#109]
Hello,
Is there a way to change the number format in table view ?

For instance, I need to see my value as "1264" instead of "1,26k".
![binjr number format](https://user-images.githubusercontent.com/19878311/111764597-a6896100-88a3-11eb-9bf1-944826d53349.png)

I seems to be simple setting that I was sure to find...    but I've searched and I've read the documentation with no success.

Thanks in advance.

**Comment by fthevenet** [comment]
Hi,
As a matter of fact, there currently isn't an option to change the number formatting, I'm afraid.
I can see how that would be useful to some use cases, however, so I'll track this as an enhancement request.

Thanks.

**Comment by mousspi** [comment]
Thank you @fthevenet for the quick answer, the enhancement request, and this really great job.
That's a pity for my use, without this formatting the tool is not so convenient, and with it it will just be the perfect tool !

**Comment by fthevenet** [comment]
There is now an option to specify the prefix unit to `none`, in addition to the existing `metric` and `binary` options, which you can set on a per-chart basis:

https://user-images.githubusercontent.com/7450507/113015394-cbbc8000-917d-11eb-8e41-c2eac8adc1d5.mp4

This will be available in the upcoming v3.0.0.
