### ISSUE TITLE
support for timestamp in milliseconds (CSVAdapter)

### ISSUE THREAD

**Issue by bozdemir84** [binjr/binjr#114]
My CSV files are with timestamps in milliseconds which would be converted to Date directly. (without parsing). 
Is there a way at the moment?

**Comment by fthevenet** [comment]
I'm afraid it is not possible at the moment.
I have been considering enhancing the csv adapter by reusing some of the features developed for the log files adapter, and amongst those is a much more powerful editor for expressing parsing rules for timestamps, that could fit the bill.

I'm going to leave this one open as a feature request, but if and when that happens will depend on me having some spare time (or someone else pitching in) so I can't give you any kind of an ETA.

**Comment by 3gyptian** [comment]
Has there been an progress?  This would be a great feature add!   Either way, thank you for this fantastic tool.

**Comment by fthevenet** [comment]
Hi, 
This issue is currently being addressed. I'm going to be looking for volunteers for testing and feedback.
Please let me know either here or #119

**Comment by fthevenet** [comment]
The CSV plugin now uses the parsing dialog from the log file adapter, with offers a lot more flexibility when defining the parsing pattern, and also allows users to save, export and import those patterns.
![image](https://user-images.githubusercontent.com/7450507/176409646-7d2d8ae4-bcf0-4ead-9530-942fd8c20b0a.png)

For the specific requests expressed in this issue, you could simply use the built-in "Milliseconds from 01/01/1970" format:
![image](https://user-images.githubusercontent.com/7450507/176409997-bda23fa6-76f0-4a04-af81-6ff9bbf1e3f1.png)
Chances are your milliseconds timestamps are not Unix style epoch, so the date itself might be wrong, but at least the times in ms should be correct.

I've published a SNAPSHOT build that you can try out here: https://github.com/binjr/binjr/releases/tag/v3.9.0-SNAPSHOT

**Comment by fthevenet** [comment]
Support added in [v3.9.0](https://github.com/binjr/binjr/releases/tag/v3.9.0)
