### ISSUE TITLE
Support for timestamp NOT in the first column (CSVAdapter)

### ISSUE THREAD

**Issue by leehangyue** [binjr/binjr#120]
Dear developers of binjr,

I was using binjr and it failed to visualize a data file of the following format (see [example_datetime_not_in_1st_col.csv](https://github.com/binjr/binjr/files/9164984/example_datetime_not_in_1st_col.csv)):
```
Id    col1    col2    col3    SaveTime
1     1.1     1.1     1.1     2022-02-02 22:22:22
2     1.1     1.1     1.1     2022-02-02 22:22:23
...
```

**The timestamps are in the fifth column instead of the first column.**

When loading the given data file, binjr threw an exception with the following stacktrace:

>      
>      java.time.format.DateTimeParseException: Text '1' could not be parsed at index 0
> 	at java.base/java.time.format.DateTimeFormatter.parseResolved0(Unknown Source)
> 	at java.base/java.time.format.DateTimeFormatter.parse(Unknown Source)
> 	at java.base/java.time.ZonedDateTime.parse(Unknown Source)
> 	at eu.binjr.sources.csv.adapters.CsvFileAdapter.lambda$decoderFactory$5(CsvFileAdapter.java:257)
> 	at eu.binjr.core.data.codec.csv.CsvDecoder.decode(CsvDecoder.java:172)
> 	at eu.binjr.sources.csv.adapters.CsvFileAdapter.buildSortedDataStore(CsvFileAdapter.java:264)
> 	at eu.binjr.sources.csv.adapters.CsvFileAdapter.getDataStore(CsvFileAdapter.java:238)
> 	at eu.binjr.sources.csv.adapters.CsvFileAdapter.getInitialTimeRange(CsvFileAdapter.java:141)
> 	at eu.binjr.core.data.workspace.Rangeable.getInitialTimeRange(Rangeable.java:57)
> 	at eu.binjr.core.controllers.XYChartsWorksheetController.addBindings(XYChartsWorksheetController.java:1311)
> 	at eu.binjr.core.controllers.XYChartsWorksheetController.handleDragDroppedOnLegendTitledPane(XYChartsWorksheetController.java:1111)
> 	at javafx.base@18.0.1/javafx.event.WeakEventHandler.handle(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventUtil.fireEventImpl(Unknown Source)
> 	at javafx.base@18.0.1/com.sun.javafx.event.EventUtil.fireEvent(Unknown Source)
> 	at javafx.base@18.0.1/javafx.event.Event.fireEvent(Unknown Source)
> 	at javafx.graphics@18.0.1/javafx.scene.Scene$DnDGesture.fireEvent(Unknown Source)
> 	at javafx.graphics@18.0.1/javafx.scene.Scene$DnDGesture.processTargetDrop(Unknown Source)
> 	at javafx.graphics@18.0.1/javafx.scene.Scene$DropTargetListener.drop(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.lambda$handleDragDrop$2(Unknown Source)
> 	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.GlassSceneDnDEventHandler.handleDragDrop(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleDragDrop$11(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleDragDrop(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.glass.ui.View.handleDragDrop(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.glass.ui.View.notifyDragDrop(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.glass.ui.win.WinDnDClipboard.push(Native Method)
> 	at javafx.graphics@18.0.1/com.sun.glass.ui.win.WinSystemClipboard.pushToSystem(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.glass.ui.SystemClipboard.flush(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.glass.ui.ClipboardAssistance.flush(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.QuantumClipboard.flush(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.startDrag(Unknown Source)
> 	at javafx.graphics@18.0.1/javafx.scene.Scene$DnDGesture.dragDetectedProcessed(Unknown Source)
> 	at javafx.graphics@18.0.1/javafx.scene.Scene$DnDGesture.process(Unknown Source)
> 	at javafx.graphics@18.0.1/javafx.scene.Scene$MouseHandler.process(Unknown Source)
> 	at javafx.graphics@18.0.1/javafx.scene.Scene.processMouseEvent(Unknown Source)
> 	at javafx.graphics@18.0.1/javafx.scene.Scene$ScenePeerListener.mouseEvent(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(Unknown Source)
> 	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.glass.ui.View.handleMouseEvent(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.glass.ui.View.notifyMouse(Unknown Source)
> 	at javafx.graphics@18.0.1/com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
> 	at javafx.graphics@18.0.1/com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(Unknown Source)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> 

I'm using binjr-3.8.0_windows-amd64 on my surface pro 5 running windows 10 64 bit home edition.

It may seem easy to swap the timestamp column and the first column with Excel or other editors, but doing so can be inconvinient in my case where data files are of sizes from 100 MB to 3 GB. Therefore, I would expect that binjr supports my data format.

Since I'm familiar with python and have some basic experience with Java, I would be glad to contribute to the code of binjr if necessary.

Leo

**Comment by fthevenet** [comment]
Hello.

Thanks for you report.

There is indeed no way to instruct binjr to look into a column other than the first one in the current version of binjr (3.8.0, as of writing).
I am, however, in the process of completely rewriting the CSV data adapter at the moment so this is definitively  an enhancement I'll consider for the next release.

I've added a note about it to the discussion used to track these changes: #119

**Comment by fthevenet** [comment]
Support added in [v3.9.0](https://github.com/binjr/binjr/releases/tag/v3.9.0)
