### ISSUE TITLE
CSV parser: Scientific number format does not accept <nn>E+<nn> as written by numpy savetxt()

### ISSUE THREAD

**Issue by jwasys** [binjr/binjr#137]
CSV parser: Scientific number format does not accept <nn>e+<nn> as written by numpy savetxt()

```
6.000000e-03 parses to 6, FAIL
6.000000E-03 parses to 0.006 OK
2.399700e+01 parses to 2.399 FAIL
2.399700E+01 parses to NaN FAIL
2.399700E01 parses to 23.99700 OK
```

Thanks for the nice program !

**Comment by fthevenet** [comment]
Hello!

This is how Java will parse those examples you provided (using [NumberFormat](https://docs.oracle.com/en/java/javase/20/docs/api/java.base/java/text/NumberFormat.html)) and there isn't a lot that can be done short of rolling out a custom parser like for the date formats, which unfortunately I cannot justify spending the time on at the moment.
