### ISSUE TITLE
Date only data series

### ISSUE THREAD

**Issue by serbuk** [binjr/binjr#138]
First of all thanks for such useful tool! I would like to use ti analyze app usage data (impressions, installs, and many others) to see correlation between different metrics. All my data is per date (without time part). Is it possible to display dates (only) on X axis? Thank you.

**Comment by fthevenet** [comment]
Hi,

I'm assuming you're reading data form CSV files? If you define a set of parsing rules that only pick up dates and omit times, the program will automatically complete it (with 00:00:00) to generate a valid timestamp, and you should be able to plot the data.

**Comment by fthevenet** [comment]
e.g.
![image](https://github.com/binjr/binjr/assets/7450507/470074d4-5eda-44ae-8d76-9bbc7df6d7a7)
