### ISSUE TITLE
Is it possible to set the default chart type?

### ISSUE THREAD

**Issue by apiszcz** [binjr/binjr#140]
Setting the default chart type would save time and might be added to the Chart Settings?

Incredible tool, thank you.

**Comment by fthevenet** [comment]
Yes, this makes a lot of sense.

**Comment by fthevenet** [comment]
I've added this, alongside the option to also pick a default for the unit prefix for a chart (i..e. the way larger values are written in short form) to a preview build that can be found here: https://github.com/binjr/binjr/releases/tag/v3.14.0-SNAPSHOT

I'd appreciate if you could give it a try and give me your feedback.

Please note that this default value for chart types is only used when the preferred chart type isn't provided by the source itself. 
This varies greatly depending on the source/adapter used (i.e. in the case of sources like RRD, the chart type is always inferred from the source, while it is never the case for CSV).

**Comment by apiszcz** [comment]
Hi, I did not locate the setting (next to the unit prefix). I was thinking of a on/off button under Settings->Charts->Default Style->pick list of styles. I am loading a CSV file so maybe this option is not present?

**Comment by fthevenet** [comment]
There is a drop-down list in settings > Charts:
![image](https://github.com/binjr/binjr/assets/7450507/0a0e235d-ce8a-4373-9005-5a781a5df29b)

**Comment by apiszcz** [comment]
Hi, 
![image](https://github.com/binjr/binjr/assets/1430861/c0228625-327d-4617-a871-361b0804600d)

**Comment by fthevenet** [comment]
You'll need to download the preview build first from here: https://github.com/binjr/binjr/releases/tag/v3.14.0-SNAPSHOT

**Comment by apiszcz** [comment]
I 'thought' i did, and clicked on the .exe directly. Is there a version attribute with it the tool? ( I like the title bar binjr - x.xx.xxx or YYYYMMDD.

About says 3.13.0. Got it.
will try again.

**Comment by fthevenet** [comment]
Yes, the version you want is v3.14.0-SNAPSHOT. That info is available in the "about" dialog.

**Comment by apiszcz** [comment]
Works great, thank you. After setting to in settings->Chart.
I quit the application, restarted, loaded another file and 'line' chart type worked no reselecting on each load.

**Comment by fthevenet** [comment]
Thanks for your feedback.
