### ISSUE TITLE
How do I display the row number for the source data on the plot?

### ISSUE THREAD

**Issue by apiszcz** [binjr/binjr#141]
Time interpretation is great.
In some cases, having the exact record number may be of use for some analysis. Is there a setting or action to show the row or record number from the data source under the cursor or with a pointer?

**Comment by fthevenet** [comment]
I am not sure I understand your question.
Do you mean is there a way to display the exact Y axis value for timestamp under the cursor?
If so this value is shown for every series in the table below the graph, in the "current" column:
![image](https://github.com/binjr/binjr/assets/7450507/9589e23e-d717-4397-81ef-0878344b4f5d)

**Comment by apiszcz** [comment]
That is the 'value', i am looking for the index or row number of the csv.  The lower display area might show 'index' or 'row' of the file or data source if avaialble.

**Comment by apiszcz** [comment]
binj is incredible, a portable kibana like tool, need to get the word out more to data science types.

**Comment by fthevenet** [comment]
> That is the 'value', i am looking for the index or row number of the csv. The lower display area might show 'index' or 'row' of the file or data source if avaialble.

Right, I see.

Unfortunately, what you ask isn't really possible in binjr.
The core concept in this tool is to be able to represent multiple times series from any supported sources on the same view (or set of synchronized views); "row number" is a concept that's relevant for a csv file, but not for other types of sources, so I can't really think of a way to surface it in the UI that could be generalized to make sense for all data sources.
