### ISSUE TITLE
Ability to handle missing values

### ISSUE THREAD

**Issue by PMunch** [binjr/binjr#143]
I was loading a CSV dump from a sensor package and some columns are empty if the specific sensor didn't deliver data within that time-range. When I open this file in binjr these missing values are treated as 0 causing a very noisy graph and incorrect averages. Would it be possible to treat these values as actually missing, or at the very least as a value in-between the surrounding values?

**Comment by fthevenet** [comment]
Hi,

I have added a new option in the "Settings > Charts" pane named "Treat undefined Y values as 0". It is set to true by default (this is the behaviour that you've noted above) but if you set it to false, undefined values (i.e. empty columns in CSV files, NaN values from numerical sources, etc...) will simply be ignored instead; they will not be plotted nor taken into account in when computing the average.

Please download this try this PREVIEW build and try it: https://github.com/binjr/binjr/releases/tag/v3.15.0-SNAPSHOT

Cheers

**Comment by PMunch** [comment]
That was fast! Works perfectly as well!
