### ISSUE TITLE
Highlighting for Log levels inside a single log file

### ISSUE THREAD

**Issue by nickmmain** [binjr/binjr#147]
This is a feature request. Mostly I am wondering if this work is being done, or is planned to be done.

I have log levels INFO, WARN, DEBUG, etc. and it would be helpful to have them each highlighted in a different color both in the chart and in the events list.

As far as I can tell, multiple parsers can't be applied to a single log file. It would be super helpful to have this functionality.

**Comment by fthevenet** [comment]
Hello!

If I understand your request correctly, this feature already exists in binjr. 

For instance, here's a screenshot of binjr's own log files parsed using the built-in "binjr logs" parsing rules:

![image](https://github.com/binjr/binjr/assets/7450507/c423d80c-cdbd-4ac6-981e-519f5ca9aef7)

If you do not see different colors for different types of event in your own log files, you'll probably need to customize the parsing rules to adapt those to your specific log format.

**Comment by nickmmain** [comment]
Brilliant ! Yes I hadn't understood how that worked. Thanks a ton.
