### ISSUE TITLE
Suggest recent sources when adding a new source

### ISSUE THREAD

**Issue by Arkanosis** [binjr/binjr#59]
… and not only when a letter has already been typed :)

**Comment by fthevenet** [comment]
URI field on the selection dialog is now a combo box; clicking the downward facing arrow on the right of the field invokes a popup that presents the full history.
The auto-compete feature that triggers when typing text directly in the field is still present (though it is disabled while button-invoked popup is visible. e.g. it isn't possible to "refine" the content of the history popup by typing text if you have clicked on the down arrow.)

**Comment by Arkanosis** [comment]
It's perfect, thanks! :)
