### ISSUE TITLE
No values shown in chart from CSV

### ISSUE THREAD

**Issue by tstuefe** [binjr/binjr#88]
[original.csv.txt](https://github.com/binjr/binjr/files/3931188/original.csv.txt)

Hi,

I have a (moderately complicated) csv which I tried binjr on. The CSV loads fine, I see all column values, but when I drag and drop (which I assume is the right way) some columns over to a chart area, nothing is shown. The vertical axis of the chart area is adjusted fine, only the chart stays empty.

I wonder, do you not recognize quotes?

I attached the example csv.

Thanks, Thomas

**Comment by fthevenet** [comment]
Hi,

The CSV file you attached does indeed reveal a bug in binjr's CSV data adapter, which becomes visible when you drop two series from csv sources with the same name on a single chart.
This will be addressed in the next release.

Also, as noted in #87, please make sure the time range of the worksheet is set so it includes the period your csv has got samples for. You can change the time range by clicking on it, at the top of the worksheet.

Thanks for your report.
Fred

**Comment by tstuefe** [comment]
Thanks a lot! This was actually a bug in our SapMachine (https://github.com/SAP/SapMachine/issues/560). I now see my charts just fine.
