### ISSUE TITLE
Cannot get 100% opacity in overlayed area charts

### ISSUE THREAD

**Issue by tstuefe** [binjr/binjr#90]
![1](https://user-images.githubusercontent.com/6041414/70340468-24f9f500-1851-11ea-9680-0aa41ac4df7a.png)
![2](https://user-images.githubusercontent.com/6041414/70340469-24f9f500-1851-11ea-81a6-d65963e168bf.png)

[original (copy).csv.txt](https://github.com/binjr/binjr/files/3933139/original.copy.csv.txt)

Linux, Ubuntu 16.4:

I add two columns (meta-comm and meta-used) to an Area Chart. I stack them in order: meta-comm, then meta-used. The area of the latter is contained in the former. 

I see the color of the background series area shine through the foreground one. E.g. meta-comm is red, meta-used blue, but meta-used appears violet. If the background series is switched off, we are back to blue.

I modified the color and even created custom colors with 100% opacity, but that seems to have no effect. I can lower opacity and that has a visible effect; but setting foreground chart opacity to 100% still makes the background shine thru.

**Comment by fthevenet** [comment]
Hi

Have you tried adjusting the "Area opacity" slider on the left pane?

![opacity](https://user-images.githubusercontent.com/7450507/70342379-275e4e00-1855-11ea-8cb6-48f916788570.gif)

**Comment by tstuefe** [comment]
Ah, thats it. Sorry!
