### ISSUE TITLE
Support SVG for saving snapshots

### ISSUE THREAD

**Issue by tstuefe** [binjr/binjr#91]
Enhancement idea.

One currently can save a snapshot of the current worksheet as PNG. It would be nice to be able to save as SVG too, since SVG can be scaled lossless and are more handy in a number of situations.

**Comment by Arkanosis** [comment]
We've had long talks about this with @fthevenet and unfortunately, it appears to be far from trivial. If you need to zoom on your snapshots like me, you might be happy to learn that he recently added an option in the settings to change the scale of snapshots, which results in bigger, more zoomable snapshots (still PNG, but the difference is noticeable).

**Comment by tstuefe** [comment]
Thanks for considering it. Never mind then, I will close the issue.
